name=Arduino-ESPSerialFlasher
version=1.0.0
author=TienHuyIoT
maintainer=TienHuyIoT
sentence=ESP Serial Flasher Arduino Library for ESP8266/ESP32
paragraph=ESP Serial Flasher Arduino Library for ESP8266/ESP32
category=Other
url=https://github.com/TienHuyIoT/Arduino-ESPSerialFlasher
architectures=*
